defmodule <%= @web_module %>.SupportWidgetLive do
  @moduledoc """
  Always-on support widget for logged-in users — a sticky nested LiveView with
  two clear intents:

    * **Chat** — a live conversation with a CodeMySpec operator.
    * **Report a problem** — file an issue (title/description/severity) that
      lands in the project's CodeMySpec issue queue.

  Both ride the same per-user `WidgetClient` Slipstream connection, authenticated
  by the project deploy key — the key never reaches the browser. Chat relays
  `send_message`/`new_message`; "Report a problem" pushes a `submit_feedback`
  event on the same conversation topic. Generated by `mix cms_gen.support_widget`.
  """

  use <%= @web_module %>, :live_view

  on_mount {<%= @web_module %>.UserAuth, :mount_current_scope}

  alias <%= @app_module %>.CodeMySpec.Widget

  @impl true
  def mount(_params, _session, socket) do
    user = socket.assigns[:current_scope] && socket.assigns.current_scope.user

    socket =
      socket
      |> assign(:user, user)
      |> assign(:open, false)
      |> assign(:tab, :chat)
      |> assign(:messages, [])
      |> assign(:fb_submitted, false)
      |> assign(:fb_error, nil)
      |> assign(:screenshot_data, nil)
      |> assign(:capturing, false)

    if connected?(socket) and user do
      Widget.ensure_started(user.id, user.email)
      Phoenix.PubSub.subscribe(<%= @pubsub %>, Widget.topic(user.id))
      %{messages: messages} = Widget.state(user.id)
      {:ok, assign(socket, :messages, messages), layout: false}
    else
      {:ok, socket, layout: false}
    end
  end

  @impl true
  def handle_event("toggle", _params, socket) do
    {:noreply, update(socket, :open, &(!&1))}
  end

  def handle_event("switch_tab", %{"tab" => tab}, socket) do
    {:noreply, assign(socket, :tab, tab_atom(tab))}
  end

  def handle_event("send", %{"message" => %{"body" => body}}, socket) do
    body = String.trim(body)

    if body != "" and socket.assigns.user do
      Widget.send_message(socket.assigns.user.id, body)
    end

    {:noreply, socket}
  end

  def handle_event("load_older", _params, socket) do
    with %{user: user} when not is_nil(user) <- socket.assigns,
         before when is_binary(before) <- oldest_cursor(socket.assigns.messages) do
      Widget.load_older(user.id, before)
    end

    {:noreply, socket}
  end

  def handle_event("capture_start", _params, socket) do
    {:noreply, assign(socket, :capturing, true)}
  end

  def handle_event("screenshot_captured", %{"data" => data_url}, socket) do
    {:noreply, socket |> assign(:screenshot_data, data_url) |> assign(:capturing, false)}
  end

  def handle_event("remove_screenshot", _params, socket) do
    {:noreply, assign(socket, :screenshot_data, nil)}
  end

  def handle_event("submit_feedback", params, socket) do
    title = String.trim(params["title"] || "")
    description = String.trim(params["description"] || "")
    severity = params["severity"] || "medium"

    cond do
      is_nil(socket.assigns.user) ->
        {:noreply, socket}

      title == "" ->
        {:noreply, assign(socket, :fb_error, "Please add a short summary.")}

      true ->
        Widget.submit_feedback(socket.assigns.user.id, %{
          "title" => title,
          "description" => description,
          "severity" => severity,
          "screenshot" => socket.assigns.screenshot_data
        })

        {:noreply,
         socket
         |> assign(:fb_submitted, true)
         |> assign(:fb_error, nil)
         |> assign(:screenshot_data, nil)}
    end
  end

  def handle_event("reset_feedback", _params, socket) do
    {:noreply, assign(socket, :fb_submitted, false)}
  end

  @impl true
  def handle_info({:new_message, payload}, socket) do
    {:noreply, assign(socket, :messages, socket.assigns.messages ++ [payload])}
  end

  def handle_info({:messages, messages}, socket) do
    {:noreply, assign(socket, :messages, messages)}
  end

  def handle_info(_message, socket), do: {:noreply, socket}

  defp oldest_cursor([%{"inserted_at" => ts} | _]), do: ts
  defp oldest_cursor(_), do: nil

  defp tab_atom("feedback"), do: :feedback
  defp tab_atom(_), do: :chat

  @impl true
  def render(assigns) do
    ~H"""
    <div
      :if={@user}
      id="codemyspec-support-widget"
      phx-hook=".CmsScreenshot"
      class="fixed bottom-4 right-4 z-50"
    >
      <script :type={Phoenix.LiveView.ColocatedHook} name=".CmsScreenshot">
        export default {
          mounted() {
            this.el.addEventListener("click", async (e) => {
              if (!e.target.closest("[data-capture-screenshot]")) return
              this.pushEvent("capture_start", {})
              try {
                const { toPng } = await import("html-to-image")
                const dataUrl = await toPng(document.body, { cacheBust: true, pixelRatio: 1 })
                this.pushEvent("screenshot_captured", { data: dataUrl })
              } catch (err) {
                console.error("Screenshot capture failed:", err)
                this.pushEvent("screenshot_captured", { data: null })
              }
            })
          },
        }
      </script>

      <button
        type="button"
        phx-click="toggle"
        data-test="widget-toggle"
        class="btn btn-primary btn-circle shadow-lg"
        aria-label="Support"
      >
        <.icon :if={!@open} name="hero-chat-bubble-oval-left" class="size-6" />
        <.icon :if={@open} name="hero-x-mark" class="size-6" />
      </button>

      <div
        :if={@open}
        data-test="widget-panel"
        class="absolute bottom-16 right-0 flex max-h-[32rem] w-80 flex-col overflow-hidden rounded-box border border-base-300 bg-base-100 shadow-xl"
      >
        <div class="shrink-0 border-b border-base-300 bg-base-200/50 px-4 py-3">
          <p class="font-semibold">How can we help?</p>
        </div>

        <div role="tablist" class="tabs tabs-bordered shrink-0">
          <button
            role="tab"
            phx-click="switch_tab"
            phx-value-tab="chat"
            data-test="tab-chat"
            class={["tab gap-1.5", @tab == :chat && "tab-active"]}
          >
            <.icon name="hero-chat-bubble-left-right" class="size-4" /> Chat
          </button>
          <button
            role="tab"
            phx-click="switch_tab"
            phx-value-tab="feedback"
            data-test="tab-feedback"
            class={["tab gap-1.5", @tab == :feedback && "tab-active"]}
          >
            <.icon name="hero-flag" class="size-4" /> Report a problem
          </button>
        </div>

        <%!-- Chat --%>
        <div :if={@tab == :chat} data-test="chat-pane" class="flex min-h-0 flex-1 flex-col">
          <div data-test="chat-messages" class="flex-1 space-y-2 overflow-y-auto p-3">
            <button
              :if={@messages != []}
              type="button"
              phx-click="load_older"
              data-test="chat-load-older"
              class="btn btn-ghost btn-xs w-full"
            >
              Load older messages
            </button>

            <p :if={@messages == []} class="py-8 text-center text-sm text-base-content/60">
              Send a message and our team will reply here.
            </p>

            <div
              :for={message <- @messages}
              data-test="chat-message"
              data-role={message["role"]}
              class={["chat", if(message["role"] == "user", do: "chat-end", else: "chat-start")]}
            >
              <div class="chat-bubble whitespace-pre-wrap break-words">{message["body"]}</div>
            </div>
          </div>

          <form phx-submit="send" data-test="chat-form" class="flex gap-2 border-t border-base-300 p-3">
            <input
              type="text"
              name="message[body]"
              data-test="chat-input"
              placeholder="Type a message…"
              autocomplete="off"
              class="input input-bordered input-sm flex-1"
            />
            <button type="submit" class="btn btn-primary btn-sm" aria-label="Send">
              <.icon name="hero-paper-airplane" class="size-4" />
            </button>
          </form>
        </div>

        <%!-- Report a problem --%>
        <div :if={@tab == :feedback} data-test="feedback-pane" class="min-h-0 flex-1 overflow-y-auto p-4">
          <div :if={@fb_submitted} class="py-6 text-center" data-test="feedback-thanks">
            <.icon name="hero-check-circle" class="mx-auto size-10 text-success" />
            <p class="mt-2 text-sm font-medium">Thanks — we've logged it.</p>
            <p class="text-xs text-base-content/60">Our team will take a look.</p>
            <button type="button" phx-click="reset_feedback" class="btn btn-ghost btn-xs mt-3">
              Report another
            </button>
          </div>

          <form
            :if={!@fb_submitted}
            phx-submit="submit_feedback"
            data-test="feedback-form"
            class="space-y-3"
          >
            <p class="text-xs text-base-content/60">
              Found a bug or have a request? Tell us what happened.
            </p>

            <div :if={@fb_error} class="alert alert-error p-2 text-xs" data-test="feedback-error">
              <span>{@fb_error}</span>
            </div>

            <label class="block">
              <span class="mb-1 block text-xs font-medium">Summary</span>
              <input
                type="text"
                name="title"
                data-test="feedback-title"
                placeholder="e.g. Save button does nothing"
                required
                class="input input-bordered input-sm w-full"
              />
            </label>

            <label class="block">
              <span class="mb-1 block text-xs font-medium">What happened?</span>
              <textarea
                name="description"
                data-test="feedback-description"
                placeholder="Steps, what you expected, what you saw…"
                rows="4"
                class="textarea textarea-bordered textarea-sm w-full"
              ></textarea>
            </label>

            <label class="block">
              <span class="mb-1 block text-xs font-medium">Severity</span>
              <select name="severity" class="select select-bordered select-sm w-full">
                <option value="low">Low — minor annoyance</option>
                <option value="medium" selected>Medium — something's off</option>
                <option value="high">High — blocks my work</option>
                <option value="critical">Critical — nothing works</option>
              </select>
            </label>

            <div :if={@screenshot_data} class="relative" data-test="screenshot-preview">
              <img src={@screenshot_data} class="w-full rounded border border-base-300" alt="Screenshot" />
              <button
                type="button"
                phx-click="remove_screenshot"
                class="btn btn-circle btn-error btn-xs absolute right-1 top-1"
                aria-label="Remove screenshot"
              >
                ×
              </button>
            </div>

            <button
              :if={!@screenshot_data && @capturing}
              type="button"
              class="btn btn-ghost btn-xs w-full border-dashed border-base-300"
              disabled
            >
              <.icon name="hero-arrow-path" class="size-4 animate-spin" /> Capturing…
            </button>
            <button
              :if={!@screenshot_data && !@capturing}
              type="button"
              data-capture-screenshot
              data-test="capture-screenshot"
              class="btn btn-ghost btn-xs w-full border-dashed border-base-300"
            >
              <.icon name="hero-camera" class="size-4" /> Attach a screenshot
            </button>

            <button type="submit" class="btn btn-primary btn-sm w-full" data-test="feedback-submit">
              Send report
            </button>
          </form>
        </div>
      </div>
    </div>
    """
  end
end
