defmodule <%= app_module %>.CodeMySpec.Widget do
  @moduledoc """
  Public interface to a user's support `WidgetClient`. Starts one Slipstream
  client per user on demand (under the app's DynamicSupervisor, keyed in the
  Registry) and exposes chat send / pagination / feedback / state to
  `SupportWidgetLive`. Generated by `mix cms_gen.support_widget`.
  """

  alias <%= app_module %>.CodeMySpec.WidgetClient

  @registry <%= app_module %>.CodeMySpec.WidgetRegistry
  @supervisor <%= app_module %>.CodeMySpec.WidgetSupervisor

  @doc "Registry `:via` tuple for a user's client process."
  def via(user_id), do: {:via, Registry, {@registry, to_string(user_id)}}

  @doc "PubSub topic SupportWidgetLive subscribes to for a user's message updates."
  def topic(user_id), do: "codemyspec:widget:#{user_id}"

  @doc "Starts the user's client if not already running. Idempotent."
  def ensure_started(user_id, user_email) do
    spec = {WidgetClient, [user_id: to_string(user_id), user_email: user_email]}

    case DynamicSupervisor.start_child(@supervisor, spec) do
      {:ok, pid} -> {:ok, pid}
      {:error, {:already_started, pid}} -> {:ok, pid}
      :ignore -> {:error, :not_configured}
      other -> other
    end
  end

  @doc "Current accumulated messages for the user (for a freshly-mounted widget)."
  def state(user_id) do
    GenServer.call(via(user_id), :state)
  catch
    :exit, _ -> %{messages: []}
  end

  def send_message(user_id, body), do: cast(user_id, {:send_message, body})
  def load_older(user_id, before), do: cast(user_id, {:load_older, before})

  @doc "Ask CodeMySpec for a presigned S3 URL to upload a screenshot to."
  def request_screenshot_upload(user_id, content_type),
    do: cast(user_id, {:request_screenshot_upload, content_type})

  @doc "Report a problem (title/description/severity) — filed as a CodeMySpec issue."
  def submit_feedback(user_id, payload), do: cast(user_id, {:submit_feedback, payload})

  defp cast(user_id, message) do
    GenServer.cast(via(user_id), message)
  catch
    :exit, _ -> :ok
  end
end
